### ISSUE TITLE
primitives get function

### ISSUE THREAD

**Issue by EthanGriffee** [LalBirali/A1P2#11]
I do not think we can write a get function that returns int, float, boolean, because Array's get returns an object and intarray is a subclass of Array.

**Comment by LalBirali** [comment]
we did not make get virtual, so there would not be any issues there, i'll also add tests shortly

**Comment by EthanGriffee** [comment]
I don't think a virtual function overrides the return type though

**Comment by LalBirali** [comment]
no, but if you call the StringArray get() it won't go to the get() of the superclass because they are essentially different methods

**Comment by LalBirali** [comment]
also, all new tests added

**Comment by EthanGriffee** [comment]
> ./Array.h:452:9: error: virtual function 'get' has a different return type ('int') than the function it overrides
      (which has return type 'Object *')
    int get(size_t index);

I get this error when trying to do that

**Comment by LalBirali** [comment]
let me see if removing virtual everywhere fixes it, this is the problem i guess overall with having this janky inheritance, sigh

**Comment by LalBirali** [comment]
try now

**Comment by EthanGriffee** [comment]
No it does not work because you cannot override get with a different return type

**Comment by LalBirali** [comment]
no i understand the problem, that's my bad. I think what is most prudent here is to because of this issue, and bc there's gonna be much code duplication, i'm going to have the other arrays extend object instead of array, bc functionally there is nothing that's actually being used from the super class, and that should be good

**Comment by LalBirali** [comment]
pushed, this should work now

**Comment by EthanGriffee** [comment]
thanks, can you just add this to take in a string
https://github.com/LalBirali/A1P2/blob/2e0629c23d2ace011a382c886f221577a847c3d7/Array.h#L247

**Comment by EthanGriffee** [comment]
and the add function that just takes in an object

**Comment by LalBirali** [comment]
done!
