### ISSUE TITLE
Add objects in clear

### ISSUE THREAD

**Issue by EthanGriffee** [LalBirali/A1P2#12]
https://github.com/LalBirali/A1P2/blob/91cf135bca431356dd893cd2f6b1f0d2840d4651/test-array.cpp#L50

Can you add all other objects declared in init conditions? Thanks.

**Comment by LalBirali** [comment]
apologies for the delay, my partner is working on the tests, i will delete the others as well.

**Comment by LalBirali** [comment]
done!

**Comment by EthanGriffee** [comment]
clear is still missing delete arr4;
