### ISSUE TITLE
More Deletes Needed

### ISSUE THREAD

**Issue by EthanGriffee** [LalBirali/A1P2#13]
https://github.com/LalBirali/A1P2/blob/48b5a0a8f5c0465be25ce9ddd04a96451cbddbfb/test-array.cpp#L212

Hi can you change this so that it deletes the value stored in starr4 before this assignment?

Also delete arr4; was not included in init conditions.

**Comment by EthanGriffee** [comment]
Also delete t in main

**Comment by EthanGriffee** [comment]
Also can you seperate the deletes of sub1, sub2, sub3

**Comment by LalBirali** [comment]
i think these should be fixed
