### ISSUE TITLE
Reconcile string.h/object.h

### ISSUE THREAD

**Issue by ZiyiPeng** [LalBirali/A1P2#2]
We are currently trying to reconcile the differences between object.h and string.h between the three teams.
I think the easiest way is to only add basic functionalities to object and string class
These methods should be enough to implement all data structures in the assignment

object:
virtual size_t hash()
virtual bool equals(Object* object)

String:
int compare_to()
String* concat(String* other)

**Comment by LalBirali** [comment]
I think this is probably agreeable, but also the constructors and destructors would have to be appropriately designed as well, and should probably stay in addition to the methods you've highlighted above. The hash_me() is something we don't really see as necessary either to cache that value. Wondering your thoughts on the constructors/destructors and a size() function which seems like its a part of the core functionality for a string. Technically core functionality would also include substring, reverse, etc. 

For this assignment, though I think the focus is most certainly the data structure, the string class probably isn't meant to be so minimal? thoughts on that?

**Comment by ZiyiPeng** [comment]
Can you change object.h and string.h according to the professor's post? Both of my other partnered teams have agreed on this design. Thanks, I know this is painful. 
* Object class has:
	* `equals(Object* other)` for checking if two objects are equal.
	* `size_t hash()` for generating a hash-number unique to this Object.
	* `to_string()` that returns a char* representation of the Object.
	* `print()` for printing a representation of this Object to the console.
* String class has:
	* `size_t size()` which gives the length of the String.
	* `equals(Object* other)` for checking if the String is equal to a given Object.
	* `compare(String* other)` for lexicographically comparing two String.
	* `hash()` for generating a unique hash code for this String.
	* `concat(String* other)` for concatenating two Strings into one.
	* `to_string()` which returns the char* representation of this String.
	* `print()` which prints this String to the console.

**Comment by LalBirali** [comment]
done! lmk if you are encountering any issues
