### ISSUE TITLE
Issues with testAddWithIndex

### ISSUE THREAD

**Issue by EthanGriffee** [LalBirali/A1P2#4]
Shouldn't these two code lines have a instead of b, because before the add a is in slot 1 and b is in slot 0

https://github.com/LalBirali/A1P2/blob/fdd1a90021f5f53333334d53a18dbfbe4e291b13/test.cpp#L78

https://github.com/LalBirali/A1P2/blob/fdd1a90021f5f53333334d53a18dbfbe4e291b13/test.cpp#L81

**Comment by LalBirali** [comment]
Yes! Good catch. I will amend shortly.

**Comment by LalBirali** [comment]
Amended
