### ISSUE TITLE
Add IntArray, FloatArray, BoolArray and tests to support primitive data type

### ISSUE THREAD

**Issue by ZiyiPeng** [LalBirali/A1P2#6]
Hi, for this assignment, Array also has to support primitive data types. Could you add these classes of arrays and keep the method's name but change their signature (type of input parameters and return type of methods)? Since we are not allowed to use the template, I think this is the easiest way to support primitives.

**Comment by LalBirali** [comment]
i will add those, do you think its harder or significantly more work to just implement the wrappers, and then only implement the array one time?

**Comment by ZiyiPeng** [comment]
No, instead, i think it would be easier to use a wrapper. But it will bring down the structure's performance and might confuse the user. For example, a user cannot use the array like this:
list.push_back(1)
int i = list.get(0)
there's a discussion on piazza about how to support primitive data type, 
https://piazza.com/class/k51bluky59n2jr?cid=369
https://piazza.com/class/k51bluky59n2jr?cid=331
the professor also hinted separated definition of different types of array is preferable.  
i think defining a separate class to represent each type of array is a better choice. 
Thanks for responding so quickly!

**Comment by LalBirali** [comment]
done!

**Comment by EthanGriffee** [comment]
Can you add tests for these classes? Also I think a test for pushing a non-String into StringArray ect. are needed.
