### ISSUE TITLE
starr should be starr3

### ISSUE THREAD

**Issue by EthanGriffee** [LalBirali/A1P2#9]
I believe starr should be starr 3 on these lines

https://github.com/LalBirali/A1P2/blob/cb0fcd764ebff416f131591922b40704c63ade17/test.cpp#L191

https://github.com/LalBirali/A1P2/blob/cb0fcd764ebff416f131591922b40704c63ade17/test.cpp#L193

https://github.com/LalBirali/A1P2/blob/cb0fcd764ebff416f131591922b40704c63ade17/test.cpp#L195

Thanks!

**Comment by LalBirali** [comment]
done!
